# Generated by Django 5.1.3 on 2024-11-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
